version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  logstash:
    image: logstash:8.12.1
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir # Mount logstash config directory
      - ./data/:/logstash_dir/data/ # Mount data directory for the CSV file
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    image: kibana:8.12.1
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      xpack.security.enabled: "false"
      NODE_OPTIONS: "--max-old-space-size=2048"
      xpack.screenshotting.browser.chromium.disableSandbox: "true"
      xpack.encryptedSavedObjects.encryptionKey: ""
      xpack.reporting.encryptionKey: ""
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
